#%RAML 1.0 Trait


headers:
  x-vio-transactionId:
    required: true
    type: string
    minLength: 36
    maxLength: 36
    example: "dbfhjsdb-hfb-do8ryt-876utt7-5ty364ol"
  clientId:
    required: true
    type: string
    example: "hsdfgysdhfcdshf37er6twgsdhfjcd"
  clientSecret:
    required: true
    type: string
    example: "dsgfhaegur457r6ewsewegrfjesh"
