#%RAML 1.0 DataType

type: object
properties:
  eventInstanceId:
    type: string
    required: true
    example: "dsfhdbfhsbdfhjsb3784t2wfsd"
  status:
    type: string
    required: true
    example: "success"
example: !include ../example/health-check-example.json