#%RAML 1.0 DataType

type: object
properties:
  email:
    required: true
    type: string
    example: "muletraining@abc.com"
    pattern: ^.+@.+\..+$
  otp:
    type: string
    required: true
    example: "dsgshheu"
  newPassword:
    required: true
    type: string
    example: "dgdhdyejnjd"
  confirmNewPassword:
    required: true
    type: string
    example: "dgdhdyejnjd"

example: !include ../example/password-reset-request-example.json

